from tkinter import Tk, Canvas, Frame, Label, Entry, Button, Scrollbar, Listbox
import MVC

window_width = 1500
windows_height = 700

root = Tk()
root.title('MazesGUI')
canvas = Canvas(root, width=window_width, height=windows_height, relief='raised')
canvas.pack()

top_frame = Frame(root, bg="grey")
top_frame.place(relwidth=1, relheight=0.1)
header = Label(top_frame, text='Maze Solver', bg="grey")
header.config(font=('lucida console', 19))
header.place(relx=0.45, rely=0.45)

frame_center = Frame(root, bg="grey")
frame_center.place(relwidth=0.45, relheight=0.7, relx=0.3, rely=0.1)
filename_label = Label(frame_center)
filename_label.place(relwidth=1, relheight=1)
frame_center_window = Frame(frame_center, bd=1, bg="black")
frame_center_window.place(relwidth=0.9, relheight=0.9, relx=0, rely=0.1)
label_center = Label(frame_center_window)
label_center.place(relwidth=1, relheight=1)
display_maze = Label(label_center, bg="white")
display_maze.place(relwidth=1, relheight=1)

frame_left_side = Frame(root, bg='grey')
frame_left_side.place(relwidth=0.3, relheight=0.9, rely=0.1)
label_maze_list = Label(frame_left_side, text='Generate mazes:', bg="gray", font=('helvetica', 12, 'bold'))
label_maze_list.place(relx=0.1, rely=0.075)
label_maze_size = Label(frame_left_side, text='Choose a maze size:', bg="gray", font=('helvetica', 8, 'bold'))
label_maze_size.place(relx=0.1, rely=0.2)
input_maze_size = Entry(frame_left_side)
input_maze_size.place(relx=0.1, rely=0.24, relwidth=0.6, relheight=0.05)
label_maze_number = Label(frame_left_side, text='Choose a number of mazes:', bg="gray", font=('helvetica', 8, 'bold'))
label_maze_number.place(relx=0.1, rely=0.3)
input_maze_number = Entry(frame_left_side)
input_maze_number.place(relx=0.1, rely=0.34, relwidth=0.6, relheight=0.05)
button_generate_maze = Button(frame_left_side, text='Generate', bg='brown', fg='white', font=('helvetica', 9, 'bold'), command=lambda: "MAZEGEN HERE")
button_generate_maze.place(relx=0.1, rely=0.425, relwidth=0.6, relheight=0.05)
label_log = Label(frame_left_side, text='Helping log:', bg="gray", font=('helvetica', 8, 'bold'))
label_log.place(relx=0.1, rely=0.5)
frame_log = Frame(frame_left_side, bd=1, bg="black")
frame_log.place(relx=0.1, rely=0.55, relwidth=0.65, relheight=0.35)
fill_log = Frame(frame_log)
fill_log.place(relwidth=1, relheight=1)
text_log = Label(frame_log, text='Welcome', borderwidth=1)
text_log.config(font=('lucida console', 9))
text_log.place(relx=0.0, rely=1, anchor="sw")
hide_log = Frame(frame_left_side, bg="grey")
hide_log.place(relx=0.1, rely=1, relwidth=0.65, relheight=0.4)
button_showhide_log = Button(frame_left_side, text='Hide log', bg='brown', fg='white', font=('helvetica', 9, 'bold'), command="LOG_ACTION HERE")
button_showhide_log.place(relx=0.1, rely=0.9, relwidth=0.2, relheight=0.03)

frame_right_side = Frame(root, bg='grey')
frame_right_side.place(relwidth=0.3, relheight=0.9, rely=0.1, relx=0.75)
label_maze_list = Label(frame_right_side, text='List of mazes:', bg="gray", font=('helvetica', 12, 'bold'))
label_maze_list.place(relx=0.1, rely=0.075)
frame_maze_list_outer = Frame(frame_right_side, bd=1, bg="black")
frame_maze_list_outer.place(relx=0.1, rely=0.14, relwidth=0.65, relheight=0.635)
frame_maze_list = Frame(frame_maze_list_outer, bd=1, bg="white")
frame_maze_list.place(relwidth=1, relheight=1)
scrollbar = Scrollbar(frame_maze_list)
Listbox_maze_list = Listbox(frame_maze_list, yscrollcommand=scrollbar.set, selectbackground="brown")
button_select_maze = Button(frame_right_side, text='Select maze', command="SELECT MAZE HERE", bg='brown', fg='white', font=('helvetica', 9, 'bold'))
button_select_maze.place(relx=0.1, rely=0.838, relwidth=0.3, relheight=0.072)

frame_bottom = Frame(root, bg='grey')
frame_bottom.place(relwidth=0.45, relheight=0.2, relx=0.3, rely=0.8)
button_generate_simple = Button(frame_bottom, text='Simple Generate', command="generate_simple_mazes", bg='brown', fg='white', font=('helvetica', 9, 'bold'))
button_generate_simple.place(relx=0.0, rely=0.3, relwidth=0.2, relheight=0.3)
button_solve = Button(frame_bottom, text='Solve Maze', command="solve_single_mazes", bg='brown', fg='white', font=('helvetica', 9, 'bold'))
button_solve.place(relx=0.7, rely=0.3, relwidth=0.2, relheight=0.3)
button_plot = Button(frame_bottom, text='Show plot', command="plot_mazes", bg='brown', fg='white', font=('helvetica', 9, 'bold'))
button_plot.place(relx=0.5, rely=0.3, relwidth=0.2, relheight=0.3)

root.mainloop()